# Where to host the web server
host = "localhost"
# Port to host the web server on
port = 8080
# Amount of threads to use for the web server 
# (Will be able to handle this many requests at once)
threads = 16
# How long until a request times out (in seconds)
req_duration = 5

# The path to the database file
db_path = "./data.db"

# Configuration for docker
[docker]
tmp_folder = ""
# command to use for docker
command = "docker"
timeout = 0

# Configuration for article parsing
[parse_config]
# The url to the git repository containing the articles
git_url = "https://github.com/aspiringLich/amplitude_articles.git"
# Where to clone the aforementioned git repository to
clone_path = "./articles"
# The path to output the rendered articles
output_path = "./rendered"