host = "localhost"
port = 8080
threads = 16
req_duration = 5      # secs
db_path = "./data.db"

[docker]
tmp_folder = ""
command = "docker"
timeout = 0

[articles]
git_url = "https://github.com/aspiringLich/amplitude_articles.git"
clone_path = "./articles"
output_path = "./output"