
# Server configuration
[server]
# Where to host the web server
host = "localhost"
# Port to host the web server on
port = 8080
# Amount of threads to use for the web server 
# (Will be able to handle this many requests at once)
threads = 16
# How long until a request times out (in seconds)
req_duration = 5

# Docker configuration
[docker]
# command to use for docker
command = "docker"
# timeout on running files
timeout = 0
# where to store temporary files
tmp_folder = ""

# Article parsing configuration
[parse]
# The url to the git repository containing the articles
git_url = "https://github.com/rcsc/amplitude_articles.git"
# Where to clone the aforementioned git repository to
clone_path = "./articles"
# Where to store assets (images, etc)
asset_path = "./web/static/generated"
# The prefix to use for asset paths
asset_prefix = "./generated"
# image file extensions (non exhaustive)
image_extensions = ["png", "jpg", "jpeg", "gif", "svg", "bmp", "tiff", "webp"]

# # Github OAuth configuration
# [github_oauth]
# app_id = "0123456789abcdef"
# app_secret = "0123456789abcdef"

# # Google OAuth configuration
# [google_oauth]
# client_id = "0123456789-0123456789abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com"
# client_secret = "ABCDEF-0123456789abcdefgABCDEFG-abcdefgABCDEFG"
# external_url = "http://localhost:5173"
