[rust]
image_name = "rust-runner"
source_path = "src/main.rs"
extension = "rs"
delimiter = "// ---"

[python]
image_name = "python-runner"
source_path = "main.py"
extension = "py"
delimiter = "# ---"

[javascript]
image_name = "js-runner"
source_path = "main.js"
extension = "js"
delimiter = "// ---"

[c]
image_name = "c-runner"
source_path = "src/main.c"
extension = "c"
delimiter = "// ---"

[cpp]
image_name = "cpp-runner"
source_path = "src/main.cpp"
extension = "cpp"
delimiter = "// ---"

[java]
image_name = "java-runner"
source_path = "Main.java"
extension = "java"
delimiter = "// ---"
