[package]
name = "amplitude_markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "5.1.0"
pulldown-cmark = "0.9.2"
tracing = "0.1.37"
amplitude_common = { path = "../amplitude_common" }
