name: Courses
on:
  push:
    paths:
      - "courses/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          export RUST_BACKTRACE=1
          cargo r -p amplitude_markdown
